import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/SideBar/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark antialiased">
      <body className={inter.className}>
        <div className="min-h-screen dark:bg-zinc-800 flex w-full">
          <Sidebar />
          <main className="flex-1 px-4 pb-12 pl-0 lg:px-8 m-0 ml-80">
            {children}
          </main>
        </div>
      </body>
    </html>
  );

}
